services:
  backend:
    build:
      context: backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/:/code/
    ports:
      - "8000:8000"
    env_file: envs/.back.env
    depends_on:
      - database

#  frontend:
#    build:
#      context: frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/front
#    env_file: envs/.front.env

  database:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - envs/.db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
